config/routes.rb
Rails.application.routes.draw do

  resources :laura_filters
  resources :england_news
  resources :scotlands do
    get :compare, on: :collection
  end
  resources :northern_irelands
  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all


  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  root to: "scotlands#index"
  get "ngofilter", to: 'laura_filters#index'
  get "scotsprofile", to: 'scotlands#profile'
  get "scotsfilter", to: 'scotlands#index'
  get 'scotscompare', to: 'scotlands#comparison'
  get 'scotscompare_all', to: 'scotlands#compare_all'
  get "northern_irelandprofile", to: 'northern_irelands#profile'
  get "northern_irelandfilter", to: 'northern_irelands#index'
  get "northern_irelandcompare", to: 'northern_irelands#comparison'
  get "northern_irelandcompare_all", to: 'northern_irelands#compare_all'
  get "engprofile2", to: 'england_news#profile'
  get "engfilter", to: 'england_news#index'
  get "engcompare", to: 'england_news#comparison'
  get 'engcompare_all', to: 'england_news#compare_all'
  get "scotland_cookie", to: 'scotlands#add_to_cookie'
  get "scotland_cookie_remove", to: 'scotlands#remove_from_cookie'
  get "scotland_cookie_delete", to: 'scotlands#delete_cookie'
  get "ireland_cookie", to: 'northern_irelands#add_to_cookie'
  get "ireland_cookie_remove", to: 'northern_irelands#remove_from_cookie'
  get "ireland_cookie_delete", to: 'northern_irelands#delete_cookie'
  get "england_cookie", to: 'england_news#add_to_cookie'
  get "england_cookie_remove", to: 'england_news#remove_from_cookie'
  get "england_cookie_delete", to: 'england_news#delete_cookie'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/scotland.rb
# == Schema Information
#
# Table name: scotlands
#
#  charity_id                             :integer          not null, primary key
#  charity_number                         :string
#  charity_name                           :string
#  registered_date                        :string
#  known_as                               :string
#  charity_status                         :string
#  postcode                               :string
#  constitutional_form                    :string
#  previous_constitutional_form_1         :string
#  geographical_spread                    :string
#  main_operating_location                :string
#  purposes                               :string
#  beneficiaries                          :string
#  activities                             :string
#  objectives                             :string
#  principal_office_trustees_address      :string
#  website                                :string
#  most_recent_year_income                :integer
#  most_recent_year_expenditure           :integer
#  mailing_cycle                          :string
#  year_end                               :string
#  parent_charity_name                    :string
#  parent_charity_number                  :string
#  parent_charity_country_of_registration :string
#  designated_religious_body              :string
#  regulatory_type                        :string
#  created_at                             :decimal(, )      not null
#  updated_at                             :datetime         not null
#  latitude                               :float
#  longitude                              :float
#  lat                                    :float
#  lon                                    :float
#

class Scotland < ApplicationRecord
#  accepts_nested_attributes_for :postcode
  #has_many :laura_filters
  geocoded_by :postcode
  geocoded_by :main_operating_location, :latitude=>:lat , :longitude => :lon
  after_validation :geocode
#
    filterrific(
  default_filter_params: { },
  available_filters: [
    :charity_number,
    :most_recent_year_income_g,
    :most_recent_year_income_l,
    :most_recent_year_expenditure_g,
    :most_recent_year_expenditure_l,
    :purposes,
    :beneficiaries,
    :postcode,
    :main_operating_location,
    :charity_name,
    :income_range,
    :expenditure_range,
    :ngos900
  ]
)
# define ActiveRecord scopes for
# :search_query, :sorted_by, :with_country_id, and :with_created_at_gte
  scope :charity_number, lambda { |charity_number|
    terms = charity_number.split(',')
#    terms = terms.map { |e|
#      ('%'+e.gsub('*', '%') + '%').gsub(/%+/, '%')
#    }
    where(
    terms.map { |term|
      "(scotlands.charity_number) = ?"
    }.join(' OR '),
    *terms.map {|e| [e]}.flatten
  )
  }
  scope :most_recent_year_income_g, lambda {|income|
    where('scotlands.most_recent_year_income >= ?',income)
  }
  scope :most_recent_year_income_l, lambda {|income|
    where('scotlands.most_recent_year_income <= ?', income)
  }
  scope :most_recent_year_expenditure_g, lambda {|expenditure|
    where('scotlands.most_recent_year_expenditure >= ?', expenditure)
  }
  scope :most_recent_year_expenditure_l, lambda {|expenditure|
    where('scotlands.most_recent_year_expenditure <= ?', expenditure)
  }
  scope :charity_name, lambda {|name|
    where('scotlands.charity_name ILIKE ?', "%"+name+"%")
  }
  scope :purposes, lambda {|purposes|
  return nil  if purposes.eql?("Select Purpose")
  # condition query, parse into individual keywords
  terms = purposes.downcase.split(/\s+/)

  # replace "*" with "%" for wildcard searches,
  # append '%', remove duplicate '%'s
  terms = terms.map { |e|
    ('%'+e.gsub('*', '%') + '%').gsub(/%+/, '%')
  }
  where(
    terms.map { |term|
      "(scotlands.purposes) ILIKE ?"
    }.join(' AND '),
    *terms.map {|e| [e]}.flatten
  )
}
  scope :beneficiaries, lambda {|benef|
  return nil  if benef.eql?("Select Beneficiaries")
  # condition query, parse into individual keywords
  format_benef=""
  if benef.eql?("The Elderly")
    format_benef = "Older People"
  elsif benef.eql?("The Disabled")
    format_benef= "disabilities"
  elsif benef.eql?("Youth")
    format_benef= "children"
  else
    format_benef = benef
  end

  terms = format_benef.downcase.split(/\s+/)

  # replace "*" with "%" for wildcard searches,
  # append '%', remove duplicate '%'s
  terms = terms.map { |e|
    ('%'+e.gsub('*', '%') + '%').gsub(/%+/, '%')
  }
  #Change here to make it an and/or query
  where(
    terms.map { |term|
      "(scotlands.beneficiaries) ILIKE ?"
    }.join(' AND '),
    *terms.map {|e| [e]}.flatten
  )
    }

scope :postcode, lambda {|input|
  return nil  if input[:postcode_d].blank?
  # condition query, parse into individual keywords
  terms = Scotland.near(input[:postcode_d], input[:max_range])
  #Change here to make it an and/or query
  where(
    terms.map { |term|
      " charity_id = ?"
    }.join(' OR '),
    *terms.map {|e|(e.charity_id)}.flatten
  )
    }
  scope :main_operating_location, lambda {|input|
  return nil  if input[:main].blank?
  # condition query, parse into individual keywords
  terms = Scotland.near(input[:main],input[:max_range])
  #Change here to make it an and/or query
  where(
    terms.map { |term|
      " charity_id = ?"
    }.join(' OR '),
    *terms.map {|e|(e.charity_id)}.flatten
  )
    }

  scope :income_range, lambda { |input|
    return nil if input.eql?("Select Income Range")
    clean_input = input.tr('£', '')
    cleaner_input = clean_input.tr(',', '')
    terms = cleaner_input.split(' ')
    if terms[0].eql?("More")
      where("scotlands.most_recent_year_income > ?", terms[2])
    else
      where("scotlands.most_recent_year_income > ? AND scotlands.most_recent_year_income <?", terms[0],terms[2])
    end
    }
  scope :expenditure_range, lambda { |input|
    return nil if input.eql?("Select Expenditure Range")
    clean_input = input.tr('£', '')
    cleaner_input = clean_input.tr(',', '')
    terms = cleaner_input.split(' ')
    if terms[0].eql?("More")
      where("scotlands.most_recent_year_expenditure > ?", terms[2])
    else
      where("scotlands.most_recent_year_expenditure > ? AND scotlands.most_recent_year_expenditure <?", terms[0],terms[2])
    end
    }

    scope :ngos900, -> (scotlands) do
      joins("INNER JOIN laura_filters ON scotlands.charity_name = laura_filters.name")
    end

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |result|
        csv << result.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/scotlands_controller.rb
class ScotlandsController < ApplicationController
  before_action :set_scotland, only: [:show, :edit, :update, :destroy]
  layout 'application'

  helper_method :exists_in_cookie


  # GET /scotlands
  #Methods available on Scotland index page
  def index
    #Find all charities in Scotland
    @scotlands = Scotland.all
    #Filter all charities in Scotland
    @filterrific = initialize_filterrific(Scotland, params[:filterrific]) or return
    @filtered = @filterrific.find.page(params[:scotlands])
    @scotlands = @filtered

    # Store all the ID's in a session so that they can be compared in bulk
    if !session[:sc_all_ids]
      session[:sc_all_ids] ||= []
    else
      session.delete(:sc_all_ids)
    end
      session[:sc_all_ids] ||= []

    #Split all charities into pages
    @filtered.paginate(page: params[:page], per_page: 1000).each do |s|
      session[:sc_all_ids] << s.charity_number
    end

    #Split all charities into pages
    @scotlands = @scotlands.paginate(page: params[:page], per_page: 20)
    respond_to do |format|
      format.html
      format.js
      format.csv {
          send_data @filtered.paginate(page: params[:page], per_page: 1000).to_csv
        }
    end

    if !session[:scotsids]
      session[:scotsids] ||= []
    end
    #Methods to see the compare queue, adding and removing cookies
    @compareQueue = session[:scotsids]
    @addcookie = scotland_cookie_path
    @rmcookie = scotland_cookie_remove_path
  end

  #Methods available in comparison
  def comparison
    #Finds all charities selected for comparison
    @compare = Scotland.where(charity_number: session[:scotsids])
    operate=[]
    address=[]
    #Find addresses of all charities being compared
    @compare.each do |a|
      address.push(a.principal_office_trustees_address)
    end
    #Find operating locations of charities being compared
    @compare.each do |b|
      address1 = b.main_operating_location
      operate.push(address1)
    end
    @address = address
    @operate = operate
    #Allows downloading of charities being compared
    @download = Scotland.where(charity_number: session[:scotsids])
    respond_to do |format|
      format.html
      format.js
      format.csv {
        send_data @download.paginate(page: params[:page], per_page: 1000).to_csv
      }
    end
  end

  def cookie
    session[:scotsids] ||= []
  end

  #Allows adding of a cookie
  def add_to_cookie
    id = params[:id]
    if session[:scotsids].include? id
      return "error"
    else
      cookie << id
    end
  end

  #Allows deleting of a cookie
  def delete_cookie
    session.delete(:scotsids)
    redirect_to scotsfilter_path
  end

  #Allows removal of an id from a cookie
  def remove_from_cookie
    id = params[:id]
    if exists_in_cookie(id)
      cookie.delete(id)
    end
  end

  #Check if an id exists in a cookie
  def exists_in_cookie(x)
    if session[:scotsids].include? x
      return true
    else
      return false
    end
  end

  #Adds all ids to a cookie and redirects to the compare page
  def compare_all
    session[:sc_all_ids].each do |s|
      if session[:scotsids].include? s
      else
        cookie << s
      end
    end
    redirect_to scotscompare_path
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scotland
      @scotland = Scotland.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def scotland_params
      params.require(:scotland).permit(:charity_number, :charity_name, :registered_date, :known_as, :charity_status, :postcode,:constitutional_form, :previous_constitutional_form_1, :geographical_spread, :main_operating_location, :purposes, :beneficiaries, :activities, :objectives, :principal_office_trustees_address, :website, :most_recent_year_income, :most_recent_year_expenditure, :mailing_cycle, :year_end, :parent_charity_name, :parent_charity_number, :parent_charity_country_of_registration, :designated_religious_body, :regulatory_type,{ :postcode_attributes => [:postcode_d, :max_range]},{ :main_operating_location_attributes => [:main, :max_range]})
    end
end

app/helpers/scotlands_helper.rb
module ScotlandsHelper
end

app/views/scotlands/_form.html.haml
= simple_form_for(@scotland) do |f|
  = f.error_notification

  .form-inputs
    = f.input :id
    = f.input :Charity_Number
    = f.input :Charity_Name
    = f.input :Registered_Date
    = f.input :Known_As
    = f.input :Charity_Status
    = f.input :Postcode
    = f.input :Constitutional_Form
    = f.input :Previous_Constitutional_Form_1
    = f.input :Geographical_Spread
    = f.input :Main_Operating_Location
    = f.input :Purposes
    = f.input :Beneficiaries
    = f.input :Activities
    = f.input :Objectives
    = f.input :Principal_Office_Trustees_Address
    = f.input :Website
    = f.input :Most_recent_year_income
    = f.input :Most_recent_year_expenditure
    = f.input :Mailing_cycle
    = f.input :Year_end
    = f.input :Parent_charity_name
    = f.input :Parent_charity_number
    = f.input :Parent_charity_country_of_registration
    = f.input :Designated_religious_body
    = f.input :Regulatory_type

  .form-actions
    = f.button :submit

app/views/scotlands/comparison.html.haml
#page-content-wrapper.container{:role => "main"}

  .row
    .col-md-12.page-header
      %h2 Comparing Charities

  .row
    .col-md-12
      .panel.panel-default
        .panel-heading
          %h3.panel-title Comparing the following NGOs:
        .panel-body
          %p
            -@compare.each do |a|
              =" #{a.charity_name},"
          %p
            =link_to "Export Data (CSV)", scotscompare_path(format: "csv"), :class => "button btn btn-primary"

  %p NOTICE: All data is from the financial year 2015/16
  .row
    .col-md-12
      %ul.nav.nav-tabs
        %li.active{:role => "presentation"}
          %a{:href => "#expenditure"} Expenditure
        %li{:role => "presentation"}
          %a{:href => "#income"} Income
        %li{:role => "presentation"}
          %a{:href => "#hq"} Headquarters Locations
        %li{:role => "presentation"}
          %a{:href => "#oploc"} Operating Location
      %br/
      %a{:name => "expenditure"}
  .row
    .col-md-12
      =column_chart @compare.map {|a| [a.charity_name, a.most_recent_year_expenditure]}

  .row.margin-top-30
    .col-md-12
      %ul.nav.nav-tabs
        %li{:role => "presentation"}
          %a{:href => "#expenditure"} Expenditure
        %li.active{:role => "presentation"}
          %a{:href => "#income"} Income
        %li{:role => "presentation"}
          %a{:href => "#hq"} Headquarters Locations
        %li{:role => "presentation"}
          %a{:href => "#oploc"} Operating Location
      %a{:name => "income"}

  .row.margin-top-30
    .col-md-12
      =column_chart @compare.map {|a| [a.charity_name, a.most_recent_year_income]}

  .row.margin-top-30
    .col-md-12
      %ul.nav.nav-tabs
        %li{:role => "presentation"}
          %a{:href => "#expenditure"} Expenditure
        %li{:role => "presentation"}
          %a{:href => "#income"} Income
        %li.active{:role => "presentation"}
          %a{:href => "#hq"} Headquarters Locations
        %li{:role => "presentation"}
          %a{:href => "#oploc"} Operating Location
      %a{:name => "hq"}

  .row.margin-top-15
    .col-md-12
      #map{style: 'height:400px; background: #333;'}
        :javascript
          var locations = #{raw @address};
          var map = new GMaps({
            div: '#map',
            lat: 53.3809409,
            lng: -1.4879469,
            zoom: 4
          });
          for (var i = 0; i < #{@address.length}; i++) {
            GMaps.geocode({
              address: locations[i],
              callback: function(results, status) {
                if (status == 'OK') {
                  var latlng = results[0].geometry.location;
                  map.addMarker({
                    lat: latlng.lat(),
                    lng: latlng.lng()
                  });
                  console.log("Marker added");
                }
              }
            });
            console.log(locations[i]);
          };
  .row.margin-top-30
    .col-md-12
      %ul.nav.nav-tabs
        %li{:role => "presentation"}
          %a{:href => "#expenditure"} Expenditure
        %li{:role => "presentation"}
          %a{:href => "#income"} Income
        %li{:role => "presentation"}
          %a{:href => "#hq"} Headquarters Locations
        %li.active{:role => "presentation"}
          %a{:href => "#oploc"} Operating Location
      %a{:name => "oploc"}

  .row.margin-top-15
    .col-md-12
      #map2{style: 'height:400px; background: #333;'}
        :javascript
          var locations2 = #{raw @operate}
          var map2 = new GMaps({
            div: '#map2',
            lat: 53.3809409,
            lng: -1.4879469,
            zoom: 4
          });
          for (var j = 0; j < #{@operate.length}; j++) {
            GMaps.geocode({
              address: locations2[j],
              callback: function(results, status) {
                if (status == 'OK') {
                  var latlng = results[0].geometry.location;
                  map2.addMarker({
                    lat: latlng.lat(),
                    lng: latlng.lng(),
                  });
                  console.log("Marker added");
                }
              }
            });
            console.log(locations2[j]);
          };

app/views/scotlands/index.html.haml
#sidebar-wrapper{"data-intro" => "You can select different parameters here to filter the search", "data-step" => "3", "data-position" => "right"}
  =form_for_filterrific @filterrific do |f|
    %ul.sidebar-nav
      %li.sidebar-brand
        Advanced Search
      %li
        =f.text_field(:charity_number ,placeholder: "Charity Number", :class=>"form-control")
      %li
        =f.select(:income_range, ["Select Income Range", "£0 to £10,000","£10,000 to £100,000","£100,000 to £500,000", "£500,000 to £1,000,000", "£1,000,000 to £10,000,000", "More than £10,000,000"], {}, :class=>"form-control")
      %li
        =f.text_field(:most_recent_year_income_g,placeholder: "Minimum Income", :class=>"form-control")
      %li
        =f.text_field(:most_recent_year_income_l,placeholder: "Maximum Income", :class=>"form-control")
      %li
        =f.select(:income_range, ["Select Income Range", "£0 to £10,000","£10,000 to £100,000","£100,000 to £500,000", "£500,000 to £1,000,000", "£1,000,000 to £10,000,000", "More than £10,000,000"], {}, :class=>"form-control")
      %li
        =f.text_field(:most_recent_year_expenditure_g, placeholder: "Minimum Expenditure", :class=>"form-control")
      %li
        =f.text_field(:most_recent_year_expenditure_l,placeholder: "Maximum Expenditure", :class=>"form-control")
      %li
        =f.select(:purposes, ["Select Purpose", "Education","Religion","Disability","Arts", "Health", "Community", "Science", "Recreation", "Poverty"], {}, :class=>"form-control")
      %li
        =f.select(:beneficiaries, ["Select Beneficiaries", "Youth","Community","The Elderly", "The Disabled", "Other"], {}, :class=>"form-control")
      %li
        =f.fields_for :postcode do |postcode_fields|
          =postcode_fields.text_field(:postcode_d,placeholder: "HQ Location", :class=>"form-control")
          =postcode_fields.range_field(:max_range, in: 1..100, :id => "ranger_1", :value => 50, :onInput =>"outputUpdate2(value)")
          %output{:for => "ranger_1", :id => "volume2", :class => "location_range"}Search within a 50 mile radius
      %li
        =f.fields_for :main_operating_location do |op_location|
          =op_location.text_field(:main,placeholder: "Operation Location", :class=>"form-control")
          =op_location.range_field(:max_range, in: 1..100, :id => "ranger", :value =>50, :onInput =>"outputUpdate(value)")
          %output{:for => "ranger", :id => "volume", :class => "location_range"}Search within a 50 mile radius
      %li
        =f.fields_for :ngos900 do |g|
          =g.label(:ngo900, "900 NGOs in SIID Study", :class=>"inlineCheckbox1")
          =g.radio_button(:ngos900, :class=>"inlineCheckbox1", :value=>"")
      %li.margin-top-15
        =submit_tag "Apply Filters", :class => "btn btn-default btn-block"
      %li
        =link_to "Reset Filters", reset_filterrific_url, :class=> "btn btn-danger btn-block"

#page-content-wrapper.container{:role => "main"}

  / Main jumbotron for a primary marketing message or call to action
  .jumbotron
    %h1 NGO Comparison Tool
    %p<
      Searching for charities from the&#160;
      %a{:href => 'https://www.oscr.org.uk'}>Scottish Charity Register (OSCR)

  .row
    .col-md-12.col-xs-12
      .alert.alert-info{:role=>"alert"}
        %p
          Here you can narrow down your choice of NGO's using the set of tools below. Simply search for a charity by its name or use the advanced filter. To compare charities, simply add them to the comparison.
        %p
          = link_to "Show me how to use the site", "", :onclick => "introJs().start(); return false", :class => "btn btn-default btn-sm"



  .row{"data-intro" => "Use this search bar to search charities by name", "data-step" => "1"}
    .col-sm-9.col-xs-9
      =form_for_filterrific @filterrific, :html=> {:id => 'searchForm'} do |f|
        =f.text_field(:charity_name, placeholder: "Search for charitities by name", class: 'form-control')

    .col-sm-3.col-xs-3
      =submit_tag "Search", class: 'button btn btn-primary btn-block', :form => "searchForm"

  .row
    .col-sm-6.col-xs-12{"data-intro" => "Click here to display or hide the advanced filters", "data-step" => "2"}
      %button#menu-toggle.btn.btn-block.btn-default{:href => "#menu-toggle", "aria-label" => "Left Align"}
        %span.glyphicon.glyphicon-align-justify{"aria-hidden" => "true"}
        Show/Hide Advanced Filters
    .col-sm-6.col-xs-12
      %button.btn.btn-block.btn-default{"aria-controls" => "collapseExample", "aria-expanded" => "false", "data-target" => "#compareQueue", "data-toggle" => "collapse", :type => "button"}
        %span.glyphicon.glyphicon-th-list{"aria-hidden" => "true"}
        Show/Hide The Comparison Queue


  .row.margin-top-15
    .col-md-12
      #compareQueue.panel.panel-info.collapse
        .panel-heading
          Comparison Queue
        .panel-body
          -@compareQueue.each do |i|
            = i


  .row.margin-top-20
    .col-md-3.col-xs-6.margin-top-5{"data-intro" => "Cick here to download the filtered charities in CSV format", "data-step" => "8"}
      =link_to "Export filtered (CSV)", scotlands_path(format: "csv"), :class => "btn btn-default btn-block"
    .col-md-3.col-xs-6.margin-top-5{"data-intro" => "Cick here to compare all the filtered charities", "data-step" => "7"}
      =submit_tag  "Compare All", :form => "indexForm", :type => "submit", :class=> "btn btn-default btn-block"
    .col-md-3.col-xs-6.margin-top-5{"data-intro" => "Cick here to remove all the charities from the comparison queue", "data-step" => "6"}
      =link_to "Clear Queue", scotland_cookie_delete_path, :class=> "btn btn-default btn-block"
    .col-md-3.col-xs-6.margin-top-5{"data-intro" => "Once you add some chairities to the queue, click here to compare them", "data-step" => "5"}
      =link_to "Compare (#{@compareQueue.length})", scotscompare_path, class: 'btn btn-block btn-default', :form => "indexForm"


  .row.margin-top-10
    .col-md-12.results-table{"data-intro" => "Here you will see all the charities that match your search parameters. Click on the &quot;Add to Compare&quot; button to add that charity to the comparison queue", "data-step" => "4", "data-position" => "top"}
      %table.table.table-bordered
        %thead
          %tr
            %th Charity Number
            %th Name
            %th Compare?
        %tbody
          =form_tag("/scotscompare_all", method: "get", :id => "indexForm") do
            -@scotlands.each do |scotland|
              %tr
                %td= scotland.charity_number
                %td= link_to scotland.charity_name, scotland
                %td
                  - if exists_in_cookie(scotland.charity_number)
                    =link_to "Remove From Comparison", scotland_cookie_path(id: scotland.charity_number), :class=> "btn btn-link btn-block active addCookie", :id=>scotland.charity_number
                  - else
                    =link_to "Add To Comparison", scotland_cookie_path(id: scotland.charity_number), :class=> "btn btn-default btn-block addCookie", :id=>scotland.charity_number
                    %input{:name => "id[]", :type => "hidden", :value => scotland.charity_number}/

  .row
    .col-md-3.col-xs-6.margin-top-5
      =link_to "Export filtered (CSV)", scotlands_path(format: "csv"), :class => "btn btn-default btn-block"
    .col-md-3.col-xs-6.margin-top-5
      =submit_tag  "Compare All", :form => "indexForm", :type => "submit", :class=> "btn btn-default btn-block"
    .col-md-3.col-xs-6.margin-top-5
      =link_to "Clear Queue", scotland_cookie_delete_path, :class=> "btn btn-default btn-block"
    .col-md-3.col-xs-6.margin-top-5
      =link_to "Compare (#{@compareQueue.length})", scotscompare_path, class: 'btn btn-block btn-default', :form => "indexForm"

  .row.margin-top-30
    .col-md-12
      =will_paginate @scotlands

  .row.margin-top-30
    .col-md-12
      %h2 About Us
      %p
        The purpose of this website is to allow users to select and compare different charities based in the UK. It uses data which are available in the public domain and which are supplied by the different charity regulators of England and Wales, Scotland and Northern Ireland.

        Users of this site can compare any group of charities that they wish. However this website is an off-shoot of a research project that examines development NGOs based in the UK. There are, therefore, more ways of exploring the international development sector on this site than for other sectors. More about information about that research project, including the sources of some of the information used in this site is available here.

        We hope you find this site useful. Feedback and comments on it are welcome. Please send these to d.brockington@sheffield.ac.uk.

:javascript
  $('#wrapper').toggleClass('toggled');

app/views/scotlands/new.html.haml
%h1 New scotland

= render 'form'

= link_to 'Back', scotlands_path

app/views/scotlands/show.html.haml
#page-content-wrapper.container{:role => "main"}

  .row
    .col-md-12.page-header
      %h2 Data for "#{@scotland.charity_name}"

  .row
    .col-md-12
      .alert.alert-info{:role=>"alert"} Below you can find financial information and contact details for "#{@scotland.charity_name}"

  .row
    .col-md-12
      %ul.nav.nav-tabs
        %li.active{:role => "presentation"}
          %a{:href => "#financialData"} Financial Data
        %li{:role => "presentation"}
          %a{:href => "#contactDetails"} Contact Details
      %br/
      %a{:name => "financialData"}
    .col-md-12
      =column_chart [["Latest Year Income", @scotland.most_recent_year_income], ["Latest Year Expenditure", @scotland.most_recent_year_expenditure]]

  .row.margin-top-30
    .col-md-12
      %ul.nav.nav-tabs
        %li{:role => "presentation"}
          %a{:href => "#financialData"} Financial Data
        %li.active{:role => "presentation"}
          %a{:href => "#contactDetails"} Contact Details
      %br/
      %a{:name => "contactDetails"}

  .row
    .col-md-8
      %p
        %b Charity number:
        = @scotland.charity_number
      %p
        %b Charity name:
        = @scotland.charity_name
      %p
        %b Registered date:
        = @scotland.registered_date
      %p
        %b Charity status:
        = @scotland.charity_status
      %p
        %b Constitutional form:
        = @scotland.constitutional_form
      %p
        %b Purposes:
        = @scotland.purposes
      %p
        %b Beneficiaries:
        = @scotland.beneficiaries
      %p
        %b Activities:
        = @scotland.activities
      %p
        %b Objectives:
        = @scotland.objectives
      %p
        %b Website:
        = @scotland.website

    .col-md-4
      %p
        %b Postcode:
        = @scotland.postcode
      %p
        %b Principal office trustees address:
        = @scotland.principal_office_trustees_address
      #map{style: 'height:400px; background: #333;'}
        :javascript
          var map = new GMaps({
            div: '#map',
            lat: -12.043333,
            lng: -77.028333
          });
          GMaps.geocode({
            address: "#{@scotland.principal_office_trustees_address}",
            callback: function(results, status) {
              if (status == 'OK') {
                var latlng = results[0].geometry.location;
                map.setCenter(latlng.lat(), latlng.lng());
                map.addMarker({
                  lat: latlng.lat(),
                  lng: latlng.lng()
                });
              }
            }
          });
  / /container