config/routes.rb
Rails.application.routes.draw do

  resources :laura_filters
  resources :england_news
  resources :scotlands do
    get :compare, on: :collection
  end
  resources :northern_irelands
  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all


  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  root to: "scotlands#index"
  get "ngofilter", to: 'laura_filters#index'
  get "scotsprofile", to: 'scotlands#profile'
  get "scotsfilter", to: 'scotlands#index'
  get 'scotscompare', to: 'scotlands#comparison'
  get 'scotscompare_all', to: 'scotlands#compare_all'
  get "northern_irelandprofile", to: 'northern_irelands#profile'
  get "northern_irelandfilter", to: 'northern_irelands#index'
  get "northern_irelandcompare", to: 'northern_irelands#comparison'
  get "northern_irelandcompare_all", to: 'northern_irelands#compare_all'
  get "engprofile2", to: 'england_news#profile'
  get "engfilter", to: 'england_news#index'
  get "engcompare", to: 'england_news#comparison'
  get 'engcompare_all', to: 'england_news#compare_all'
  get "scotland_cookie", to: 'scotlands#add_to_cookie'
  get "scotland_cookie_remove", to: 'scotlands#remove_from_cookie'
  get "scotland_cookie_delete", to: 'scotlands#delete_cookie'
  get "ireland_cookie", to: 'northern_irelands#add_to_cookie'
  get "ireland_cookie_remove", to: 'northern_irelands#remove_from_cookie'
  get "ireland_cookie_delete", to: 'northern_irelands#delete_cookie'
  get "england_cookie", to: 'england_news#add_to_cookie'
  get "england_cookie_remove", to: 'england_news#remove_from_cookie'
  get "england_cookie_delete", to: 'england_news#delete_cookie'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/england_new.rb
# == Schema Information
#
# Table name: england_news
#
#  id         :integer          not null, primary key
#  charity_id :integer
#  regno      :integer
#  subno      :integer
#  name       :string
#  orgtype    :string
#  gd         :string
#  aob        :string
#  nhs        :string
#  ha_no      :string
#  corr       :string
#  add1       :string
#  add2       :string
#  add3       :string
#  add4       :string
#  add5       :string
#  postcode   :string
#  phone      :string
#  fax        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  fystart    :datetime
#  fyend      :datetime
#  income     :integer
#  expend     :integer
#  latitude   :float
#  longitude  :float
#

class EnglandNew < ApplicationRecord
  geocoded_by :postcode
  after_validation :geocode
  filterrific(
default_filter_params: {fystart: "2016/01/01 00:00:00 +0100".to_datetime},
available_filters: [
  :id,
  :regno,
  :subno,
  :charity_name,
  :postcode,
  :income_g,
  :income_l,
  :expend_g,
  :expend_l,
  :fystart,
  :fyend,
  :postcode,
  :expenditure_range,
  :income_range,
  :ngos900
]
)
scope :regno, lambda { |charity_number|
  where('england_news.regno = ? AND england_news.fystart LIKE ?', charity_number, "2015%")
}
scope :fystart, lambda { |fy|
  where('england_news.fystart LIKE ?', "2015%")
}
scope :income_g, lambda {|income|
  where('england_news.income >= ? AND england_news.fystart LIKE ?', income, "2015%")
}
scope :income_l, lambda {|income|
  where('england_news.income <= ? AND england_news.fystart LIKE ?', income, "2015%")
}
scope :expend_g, lambda {|expenditure|
  where('england_news.expend >= ? AND england_news.fystart LIKE ?', expenditure, "2015%")
}
scope :expend_l, lambda {|expenditure|
  where('england_news.expend <= ? AND england_news.fystart LIKE ?', expenditure, "2015%")
}
scope :charity_name, lambda {|name|
  where('england_news.name ILIKE ? AND england_news.fystart LIKE ?', "%"+name+"%", "2015%")
}
scope :ngos900, -> (england_news) do
  joins("INNER JOIN laura_filters ON england_news.name = laura_filters.name")
end
scope :postcode, lambda {|input|
return nil  if input[:postcode_d].blank?
# condition query, parse into individual keywords
terms = EnglandNew.near(input[:postcode_d], input[:max_range])
#Change here to make it an and/or query
where(
  terms.map { |term|
    " (id = ? AND england_news.fystart LIKE '2015%')"
  }.join(' OR '),
  *terms.map {|e|(e.id)}.flatten,
)
  }
  scope :income_range, lambda { |input|
    return nil if input.eql?("Select Income Range")
    clean_input = input.tr('£', '')
    cleaner_input = clean_input.tr(',', '')
    terms = cleaner_input.split(' ')
    if terms[0].eql?("More")
      where("england_news.income > ? AND england_news.fystart LIKE ?", terms[2], "2015%")  
    else
      where("england_news.income > ? AND england_news.income <? AND england_news.fystart LIKE ?", terms[0],terms[2],"2015%")
    end
    }
  scope :expenditure_range, lambda { |input|
    return nil if input.eql?("Select Expenditure Range")
    clean_input = input.tr('£', '')
    cleaner_input = clean_input.tr(',', '')
    terms = cleaner_input.split(' ')
    if terms[0].eql?("More")
      where("england_news.expend > ?AND england_news.fystart LIKE ?", terms[2],"2015%")  
    else
      where("england_news.expend > ? AND england_news.expend <?AND england_news.fystart LIKE ?", terms[0],terms[2],"2015%")
    end
    }


  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |result|
        csv << result.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/england_news_controller.rb
class EnglandNewsController < ApplicationController
  before_action :set_england_news, only: [:show, :edit, :update, :destroy]
  layout 'application'

  helper_method :exists_in_cookie

  # GET /england_news
  #Methods available on the index page
  def index
    #Finds the all English charities
    @england_news = EnglandNew.all

    #Return all filtered results
    @filterrific = initialize_filterrific(EnglandNew, params[:filterrific]) or return
    @filtered = @filterrific.find.page(params[:england_news])
    @england_news = @filtered

    # Store all the ID's in a session so that they can be compared in bulk
    if !session[:eng_all_ids]
      session[:eng_all_ids] ||= []
    else
      session.delete(:eng_all_ids)
    end
      session[:eng_all_ids] ||= []

    #Sort the filtered list into pages
    @filtered.paginate(page: params[:page], per_page: 1000).each do |s|
      session[:eng_all_ids] << s.id
    end
    #Sort the filtered list into pages
    @england_news = @england_news.paginate(page: params[:page], per_page: 20)

    #Allows the downloading of the filtered list
    respond_to do |format|
      format.html
      format.js
      format.csv  {
          send_data @filtered.paginate(page: params[:page], per_page: 1000).to_csv
        }
    end

    if !session[:engids]
      session[:engids] ||= []
    end
    #Finds the ids currently in the comparison queue
    @compareQueue = session[:engids]
    #Adding and removing cookies
    @addcookie = england_cookie_path
    @rmcookie = england_cookie_remove_path
  end


  def cookie
    session[:engids] ||= []
  end

  #Allows the adding of cookies
  def add_to_cookie
    id = params[:id]
    if session[:engids].include? id
      return "error"
    else
      cookie << id
    end
  end

  #Allows deleteing of cookies
  def delete_cookie
    session.delete(:engids)
    redirect_to engfilter_path
  end

  #Allows removal of an id from a cookie
  def remove_from_cookie
    id = params[:id]
    if exists_in_cookie(id)
      cookie.delete(id)
    end
  end

  #id existence check in a cookie
  def exists_in_cookie(x)
    if session[:engids].include? x
      return true
    else
      return false
    end
  end

  #Adds all ids to a cookie and redirects to the compare page
  def compare_all
    session[:eng_all_ids].each do |s|
      if session[:engids].include? s
      else
        cookie << s
      end
    end
    redirect_to engcompare_path
  end

  # GET /england_news/1
  #Methods available on the English profile pages
  def show
    #Finds the charity that has been clicked on
    @england_new= EnglandNew.find(params[:id])
    #Puts the charity address in the format gmaps can work with
    @extract_address = @england_new.add1 + ", " + @england_new.postcode
    #Finds all of the financial data records for a given charity
    @extract_income = EnglandNew.where(regno: @england_new.regno).find_each
  end

  #Methods available on the English comparison page
  def comparison
    #Finds all details of charities selected for comparison
    @compare = EnglandNew.find(session[:engids])
    address=[]
    financials = []
    expend=[]
    income = []
    #Finds addresses of all charities selected for comparison
    @compare.each do |a|
      address.push(a.add1 + ", " + a.postcode)
    end
    #Finds financial information from 2015 for all charities selected for comparison
    @compare.each do |a|
      financials.push(EnglandNew.where('regno = ? AND fystart LIKE ?', a.regno, '2015%').find_each)
    end
    #Push all expenditure information to an array
    financials.each do |a|
      a.each do |b|
        expend.push([b.name, b.expend])
      end
    end
    #Push all income information to an array
    financials.each do |a|
      a.each do |b|
        income.push([b.name, b.income])
      end
    end
    @expend=expend
    @income=income
    @financials = financials
    @address = address

    #Allows the downloading of charity information selected for comparison
    @download = EnglandNew.where(id: session[:engids])
      respond_to do |format|
        format.html
        format.js
        format.csv {
          send_data @download.to_csv
        }
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_england_news
      @england_news = EnglandNew.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def england_news_params
      params.require(:england_news).permit(:charity_id, :regno, :subno, :name, :orgtype, :gd, :aob, :nhs, :ha_no, :corr, :add1, :add2, :add3, :add4, :add5, :postcode, :phone, :fax, :created_at, :updated_at, :fystart, :fyend, :income, :expend)
    end
end

app/helpers/england_news_helper.rb
module EnglandNewsHelper
end

app/views/england_news/_form.html.haml
= simple_form_for(@england_news) do |f|
  = f.error_notification

  .form-inputs
    = f.input :charity_id
    = f.input :regno
    = f.input :subno
    = f.input :name
    = f.input :orgtype
    = f.input :gd
    = f.input :aob
    = f.input :nhs
    = f.input :ha_no
    = f.input :corr
    = f.input :add1
    = f.input :add2
    = f.input :add3
    = f.input :add4
    = f.input :add5
    = f.input :postcode
    = f.input :phone
    = f.input :fax
    = f.input :created_at
    = f.input :updated_at
    = f.input :fystart
    = f.input :fyend
    = f.input :income
    = f.input :expend

  .form-actions
    = f.button :submit

app/views/england_news/comparison.html.haml
#page-content-wrapper.container{:role => "main"}

  .row
    .col-md-12.page-header
      %h2 Comparing Charities

  .row
    .col-md-12
      .panel.panel-default
        .panel-heading
          %h3.panel-title Comparing the following NGOs:
        .panel-body
          %p
            -@compare.each do |a|
              ="#{a.name},"
          %p
            =link_to "Download Data (CSV)", engcompare_path(format: "csv"), :class => "button btn btn-primary"

  %p NOTICE: All data is from the financial year 2015/16

  .row
    .col-md-12
      %ul.nav.nav-tabs
        %li.active{:role => "presentation"}
          %a{:href => "#expenditure"} Expenditure
        %li{:role => "presentation"}
          %a{:href => "#income"} Income
        %li{:role => "presentation"}
          %a{:href => "#hq"} Headquarters Locations
      %br/
      %a{:name => "expenditure"}
  .row
    .col-md-12
      .page-header
        %h3 Expenditure
        =column_chart @expend


  .row.margin-top-30
    .col-md-12
      %ul.nav.nav-tabs
        %li{:role => "presentation"}
          %a{:href => "#expenditure"} Expenditure
        %li.active{:role => "presentation"}
          %a{:href => "#income"} Income
        %li{:role => "presentation"}
          %a{:href => "#hq"} Headquarters Locations
      %a{:name => "income"}

  .row
    .col-mid-12
      .page-header
        %h3 Income
        =column_chart @income

  .row.margin-top-30
    .col-md-12
      %ul.nav.nav-tabs
        %li{:role => "presentation"}
          %a{:href => "#expenditure"} Expenditure
        %li{:role => "presentation"}
          %a{:href => "#income"} Income
        %li.active{:role => "presentation"}
          %a{:href => "#hq"} Headquarters Locations
      %a{:name => "hq"}

  .row.margin-top-15
    .col-md-12
      #map{style: 'height:400px; background: #333;'}
        :javascript
          var locations = #{raw @address};
          var map = new GMaps({
            div: '#map',
            lat: 53.3809409,
            lng: -1.4879469,
            zoom: 4
          });
          for (var i = 0; i < #{@address.length}; i++) {
            GMaps.geocode({
              address: locations[i],
              callback: function(results, status) {
                if (status == 'OK') {
                  var latlng = results[0].geometry.location;
                  map.addMarker({
                    lat: latlng.lat(),
                    lng: latlng.lng()
                  });
                  console.log("Marker added");
                }
              }
            });
            console.log(locations[i]);
          };

app/views/england_news/edit.html.haml
%h1 Editing england_news

= render 'form'

= link_to 'Show', @england_news
\|
= link_to 'Back', england_news_path

app/views/england_news/index.html.haml
#sidebar-wrapper
  =form_for_filterrific @filterrific do |f|
    %ul.sidebar-nav
      %li.sidebar-brand
        Advanced Search
      %li
        =f.text_field(:regno ,placeholder: "Charity Number", :class=>"form-control")
      %li
        =f.select(:income_range, ["Select Income Range", "£0 to £10,000","£10,000 to £100,000","£100,000 to £500,000", "£500,000 to £1,000,000", "£1,000,000 to £10,000,000", "More than £10,000,000"], {}, :class=>"form-control")
      %li
        =f.text_field(:income_g,placeholder: "Minimum Income", :class=>"form-control")
      %li
        =f.text_field(:income_l,placeholder: "Maximum Income", :class=>"form-control")
      %li
        =f.select(:income_range, ["Select Income Range", "£0 to £10,000","£10,000 to £100,000","£100,000 to £500,000", "£500,000 to £1,000,000", "£1,000,000 to £10,000,000", "More than £10,000,000"], {}, :class=>"form-control")
      %li
        =f.text_field(:expend_g, placeholder: "Minimum Expenditure", :class=>"form-control")
      %li
        =f.text_field(:expend_l,placeholder: "Maximum Expenditure", :class=>"form-control")
      %li
        =f.fields_for :postcode do |postcode_fields|
          =postcode_fields.text_field(:postcode_d,placeholder: "HQ Location", :class=>"form-control")
          =postcode_fields.range_field(:max_range, in: 1..100, :id => "ranger_1", :value => 50, :onInput =>"outputUpdate2(value)")
          %output{:for => "ranger_1", :id => "volume2", :class => "location_range"}Search within a 50 mile radius
      %li
        =f.fields_for :ngos900 do |g|
          =g.label(:ngo900, "900 NGOs in SIID Study", :class=>"inlineCheckbox1")
          =g.radio_button(:ngos900, :class=>"inlineCheckbox1", :value=>"")
      %li.margin-top-15
        =submit_tag "Apply Filters", :class => "btn btn-default btn-block"
      %li
        =link_to "Reset Filters", reset_filterrific_url, :class=> "btn btn-danger btn-block"


#page-content-wrapper.container{:role => "main"}
  / Main jumbotron for a primary marketing message or call to action
  .jumbotron
    %h1 NGO Comparison Tool
    %p<
      Searching for charities from the&#160;
      %a{:href => 'http://apps.charitycommission.gov.uk/showcharity/registerofcharities/RegisterHomePage.aspx'}> English Charity Commission

  .row
    .col-md-12.col-xs-12
      .alert.alert-info{:role=>"alert"} Here you can narrow down your choice of NGO's using the set of tools below. Simply search for a charity by its name or use the advanced filter. To compare charities, simply add them to the comparison.

  .row
    .col-sm-9.col-xs-9
      =form_for_filterrific @filterrific, :html=> {:id => 'searchForm'} do |f|
        =f.text_field(:charity_name, placeholder: "Search for charitities by name", class: 'form-control')

    .col-sm-3.col-xs-3
      =submit_tag "Search", class: 'button btn btn-primary btn-block', :form => "searchForm"

  .row
    .col-sm-6.col-xs-12
      %button#menu-toggle.btn.btn-block.btn-default{:href => "#menu-toggle", "aria-label" => "Left Align"}
        %span.glyphicon.glyphicon-align-justify{"aria-hidden" => "true"}
        Show/Hide Advanced Filters
    .col-sm-6.col-xs-12
      %button.btn.btn-block.btn-default{"aria-controls" => "collapseExample", "aria-expanded" => "false", "data-target" => "#compareQueue", "data-toggle" => "collapse", :type => "button"}
        %span.glyphicon.glyphicon-th-list{"aria-hidden" => "true"}
        Show/Hide The Comparison Queue


  .row.margin-top-15
    .col-md-12
      #compareQueue.panel.panel-info.collapse
        .panel-heading
          Comparison Queue
        .panel-body
          -@compareQueue.each do |i|
            = i

  .row.margin-top-30
    .col-md-3.col-xs-6
      =link_to "Export filtered (CSV)", engfilter_path(format: "csv"), :class => "btn btn-default btn-block"
    .col-md-3.col-xs-6
      =submit_tag  "Compare All", :form => "indexForm", :type => "submit", :class=> "btn btn-default btn-block"
    .col-md-3.col-xs-6
      =link_to "Clear Queue", england_cookie_delete_path, :class=> "btn btn-default btn-block"
    .col-md-3.col-xs-6
      =link_to "Compare (#{@compareQueue.length})", engcompare_path, class: 'btn btn-block btn-default', :form => "indexForm"

  .row.margin-top-30
    .col-md-12.results-table
      %table.table.table-bordered
        %thead
          %tr
            %th Charity Number
            %th Sub-Charity
            %th Name
            %th Compare?
        %tbody
          =form_tag("/engcompare_all", method: "get", :id => "indexForm") do
            -@england_news.each do |eng|
              %tr
                %td= eng.regno
                %td= eng.subno
                %td= link_to eng.name, eng
                %td
                  - if exists_in_cookie(eng.id)
                    =link_to "Remove From Comparison", england_cookie_path(id: eng.id), :class=> "btn btn-link btn-block active addCookie", :id=>eng.id
                  - else
                    =link_to "Add To Comparison", england_cookie_path(id: eng.id), :class=> "btn btn-default btn-block addCookie", :id=>eng.id
                    %input{:name => "id[]", :type => "hidden", :value => eng.id}/

  .row.margin-top-30
    .col-md-3.col-xs-6
      =link_to "Export filtered (CSV)", engfilter_path(format: "csv"), :class => "btn btn-default btn-block"
    .col-md-3.col-xs-6
      =submit_tag  "Compare All", :form => "indexForm", :type => "submit", :class=> "btn btn-default btn-block"
    .col-md-3.col-xs-6
      =link_to "Clear Queue", england_cookie_delete_path, :class=> "btn btn-default btn-block"
    .col-md-3.col-xs-6
      =link_to "Compare (#{@compareQueue.length})", engcompare_path, class: 'btn btn-block btn-default', :form => "indexForm"


  .row.margin-top-30
    .col-md-12
      =will_paginate @englands


  .row.margin-top-30
    .col-md-12
      %h2 About Us
      %p
        The purpose of this website is to allow users to select and compare different charities based in the UK. It uses data which are available in the public domain and which are supplied by the different charity regulators of England and Wales, england and Northern Ireland.

        Users of this site can compare any group of charities that they wish. However this website is an off-shoot of a research project that examines development NGOs based in the UK. There are, therefore, more ways of exploring the international development sector on this site than for other sectors. More about information about that research project, including the sources of some of the information used in this site is available here.

        We hope you find this site useful. Feedback and comments on it are welcome. Please send these to d.brockington@sheffield.ac.uk.

:javascript
  $('#wrapper').toggleClass('toggled');

app/views/england_news/new.html.haml
%h1 New england_news

= render 'form'

= link_to 'Back', england_news_path

app/views/england_news/show.html.haml
#page-content-wrapper.container{:role => "main"}

  .row
    .col-md-12.page-header
      %h2 Data for "#{@england_new.name}"

  .row
    .col-md-12
      .alert.alert-info{:role=>"alert"} Below you can find financial information and contact details for "#{@england_new.name}"


  .row
    .col-md-12
      %ul.nav.nav-tabs
        %li.active{:role => "presentation"}
          %a{:href => "#financialData"} Financial Data
        %li{:role => "presentation"}
          %a{:href => "#contactDetails"} Contact Details
      %br/
      %a{:name => "financialData"}
    .col-md-12
      %h3 Income
      =column_chart @extract_income.map {|a| [a.fystart, a.income]}
    .col-md-12
      %h3 Expenditure
      =column_chart @extract_income.map {|a| [a.fystart, a.expend]}

  .row.margin-top-30
    .col-md-12
      %ul.nav.nav-tabs
        %li{:role => "presentation"}
          %a{:href => "#financialData"} Financial Data
        %li.active{:role => "presentation"}
          %a{:href => "#contactDetails"} Contact Details
      %br/
      %a{:name => "contactDetails"}

  .row
    .col-md-8
      %p
        %b Charity number:
        = @england_new.regno
      %p
        %b Sub-Charity number:
        = @england_new.subno
      %p
        %b Charity name:
        = @england_new.name
      %p
        %b Governing Document:
        = @england_new.gd
      %p
        %b NHS Charity? (T/F):
        = @england_new.nhs
      %p
        %b Correspondent Name:
        = @england_new.corr
      %p
        %b Address Line 1:
        = @england_new.add1
      %p
        %b Address Line 2:
        = @england_new.add2
      %p
        %b Address Line 3:
        = @england_new.add3
      %p
        %b Address Line 4:
        = @england_new.add4
      %p
        %b Address Line 5:
        = @england_new.add5
      %p
        %b Phone Number:
        = @england_new.phone
      %p
        %b Fax Number:
        = @england_new.fax

    .col-md-4
      %p
        %b Postcode:
        = @england_new.postcode
      #map{style: 'height:400px; background: #333;'}
        :javascript
          var map = new GMaps({
            div: '#map',
            lat: -12.043333,
            lng: -77.028333
          });
          GMaps.geocode({
            address: "#{@extract_address}",
            callback: function(results, status) {
              if (status == 'OK') {
                var latlng = results[0].geometry.location;
                map.setCenter(latlng.lat(), latlng.lng());
                map.addMarker({
                  lat: latlng.lat(),
                  lng: latlng.lng()
                });
              }
            }
          });
  / /container