config/routes.rb
Rails.application.routes.draw do

  resources :laura_filters
  resources :england_news
  resources :scotlands do
    get :compare, on: :collection
  end
  resources :northern_irelands
  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all


  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  root to: "scotlands#index"
  get "ngofilter", to: 'laura_filters#index'
  get "scotsprofile", to: 'scotlands#profile'
  get "scotsfilter", to: 'scotlands#index'
  get 'scotscompare', to: 'scotlands#comparison'
  get 'scotscompare_all', to: 'scotlands#compare_all'
  get "northern_irelandprofile", to: 'northern_irelands#profile'
  get "northern_irelandfilter", to: 'northern_irelands#index'
  get "northern_irelandcompare", to: 'northern_irelands#comparison'
  get "northern_irelandcompare_all", to: 'northern_irelands#compare_all'
  get "engprofile2", to: 'england_news#profile'
  get "engfilter", to: 'england_news#index'
  get "engcompare", to: 'england_news#comparison'
  get 'engcompare_all', to: 'england_news#compare_all'
  get "scotland_cookie", to: 'scotlands#add_to_cookie'
  get "scotland_cookie_remove", to: 'scotlands#remove_from_cookie'
  get "scotland_cookie_delete", to: 'scotlands#delete_cookie'
  get "ireland_cookie", to: 'northern_irelands#add_to_cookie'
  get "ireland_cookie_remove", to: 'northern_irelands#remove_from_cookie'
  get "ireland_cookie_delete", to: 'northern_irelands#delete_cookie'
  get "england_cookie", to: 'england_news#add_to_cookie'
  get "england_cookie_remove", to: 'england_news#remove_from_cookie'
  get "england_cookie_delete", to: 'england_news#delete_cookie'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/laura_filter.rb
# == Schema Information
#
# Table name: laura_filters
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class LauraFilter < ApplicationRecord
end

app/controllers/laura_filters_controller.rb
class LauraFiltersController < ApplicationController
  before_action :set_laura_filter, only: [:show, :edit, :update, :destroy]

  # GET /laura_filters
  def index
    @laura_filters = LauraFilter.all
    @laura_filters = @laura_filters.paginate(page: params[:page], per_page: 20)
  end

  # GET /laura_filters/1
  def show
  end

  # GET /laura_filters/new
  def new
    @laura_filter = LauraFilter.new
  end

  # GET /laura_filters/1/edit
  def edit
  end

  # POST /laura_filters
  def create
    @laura_filter = LauraFilter.new(laura_filter_params)

    if @laura_filter.save
      redirect_to @laura_filter, notice: 'Laura filter was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /laura_filters/1
  def update
    if @laura_filter.update(laura_filter_params)
      redirect_to @laura_filter, notice: 'Laura filter was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /laura_filters/1
  def destroy
    @laura_filter.destroy
    redirect_to laura_filters_url, notice: 'Laura filter was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_laura_filter
      @laura_filter = LauraFilter.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def laura_filter_params
      params.require(:laura_filter).permit(:charity_number, :subno, :name)
    end
end

app/helpers/laura_filters_helper.rb
module LauraFiltersHelper
end

app/views/laura_filters/_form.html.haml
= simple_form_for(@laura_filter) do |f|
  = f.error_notification

  .form-inputs
    = f.input :charity_number
    = f.input :subno
    = f.input :name

  .form-actions
    = f.button :submit

app/views/laura_filters/edit.html.haml
%h1 Editing laura_filter

= render 'form'

= link_to 'Show', @laura_filter
\|
= link_to 'Back', laura_filters_path

app/views/laura_filters/index.html.haml
#page-content-wrapper.container{:role => "main"}
  / Main jumbotron for a primary marketing message or call to action
  .jumbotron
    %h1 NGO Comparison Tool

  .row
    .col-md-12.col-xs-12
      .alert.alert-info{:role=>"alert"} These are the charities that are currently in the 'Mapping the UK Development NGO Sector' research project currently being undertaken by the Global Development Institue (GDI, University of Manchester) and the Sheffield Institute for International Development (SIID, University of Sheffield). <br/> See this website for more information: <li>https://mappingdevelopmentngos.wordpress.com</li>

  .row.margin-top-10
    .col-md-12.results-table
      %table.table.table-bordered
        %thead
          %tr
            %th Name
        %tbody
          =form_tag("/scotscompare", method: "get", :id => "indexForm") do
            -@laura_filters.each do |ngo|
              %tr
                %td= ngo.name

  .row.margin-top-30
    .col-md-12
      =will_paginate @laura_filters

  .row.margin-top-30
    .col-md-12
      %h2 About Us
      %p
        The purpose of this website is to allow users to select and compare different charities based in the UK. It uses data which are available in the public domain and which are supplied by the different charity regulators of England and Wales, Scotland and Northern Ireland.

        Users of this site can compare any group of charities that they wish. However this website is an off-shoot of a research project that examines development NGOs based in the UK. There are, therefore, more ways of exploring the international development sector on this site than for other sectors. More about information about that research project, including the sources of some of the information used in this site is available here.

        We hope you find this site useful. Feedback and comments on it are welcome. Please send these to d.brockington@sheffield.ac.uk.

app/views/laura_filters/new.html.haml
%h1 New laura_filter

= render 'form'

= link_to 'Back', laura_filters_path

app/views/laura_filters/show.html.haml
%p#notice= notice

%p
  %b Charity number:
  = @laura_filter.charity_number
%p
  %b Subno:
  = @laura_filter.subno
%p
  %b Name:
  = @laura_filter.name

= link_to 'Edit', edit_laura_filter_path(@laura_filter)
\|
= link_to 'Back', laura_filters_path