config/routes.rb
Rails.application.routes.draw do

  resources :laura_filters
  resources :england_news
  resources :scotlands do
    get :compare, on: :collection
  end
  resources :northern_irelands
  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all


  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  root to: "scotlands#index"
  get "ngofilter", to: 'laura_filters#index'
  get "scotsprofile", to: 'scotlands#profile'
  get "scotsfilter", to: 'scotlands#index'
  get 'scotscompare', to: 'scotlands#comparison'
  get 'scotscompare_all', to: 'scotlands#compare_all'
  get "northern_irelandprofile", to: 'northern_irelands#profile'
  get "northern_irelandfilter", to: 'northern_irelands#index'
  get "northern_irelandcompare", to: 'northern_irelands#comparison'
  get "northern_irelandcompare_all", to: 'northern_irelands#compare_all'
  get "engprofile2", to: 'england_news#profile'
  get "engfilter", to: 'england_news#index'
  get "engcompare", to: 'england_news#comparison'
  get 'engcompare_all', to: 'england_news#compare_all'
  get "scotland_cookie", to: 'scotlands#add_to_cookie'
  get "scotland_cookie_remove", to: 'scotlands#remove_from_cookie'
  get "scotland_cookie_delete", to: 'scotlands#delete_cookie'
  get "ireland_cookie", to: 'northern_irelands#add_to_cookie'
  get "ireland_cookie_remove", to: 'northern_irelands#remove_from_cookie'
  get "ireland_cookie_delete", to: 'northern_irelands#delete_cookie'
  get "england_cookie", to: 'england_news#add_to_cookie'
  get "england_cookie_remove", to: 'england_news#remove_from_cookie'
  get "england_cookie_delete", to: 'england_news#delete_cookie'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_environment_notice.html.haml
- if display_environment_notice?
  .environment-notice.alert.alert-info
    %strong Notice:
    This is the
    %strong= Rails.env
    system.

app/views/layouts/application.html.haml
%html{:lang => "en"}
  %head
    =content_for(:title, "Charity Profile Page")
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    / The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    = favicon_link_tag
    %title NGO Comparison Tool
    / Bootstrap core CSS
    = javascript_include_tag "application"
    = javascript_include_tag "comparisons"
    :javascript
      $(function(){
        enableComparison('#{@addcookie}','#{@rmcookie}');
        toggle();
      });
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"

    %script{:src => "https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"}
    %script{:src => "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"}
    %script{:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyATlM152jGMuH88wfsXYV31am3ojUKvv2M"}

  %body

    / Fixed navbar
    %nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"data-toggle" => "collapse", "data-target" => "#navbar"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#{root_url}"} NGO Comparison Tool

        / collapse
        #navbar.collapse-navbar
          %ul.nav.navbar-nav
            /%li{:class => "#{'active' if current_page?(root_url) }"}= link_to 'NGO Comparison Tool', root_url
            %li{:class => "#{'active' if current_page?(scotsfilter_url) }"}=  link_to "Scotland", scotsfilter_url
            %li{:class => "#{'active' if current_page?(northern_irelandfilter_url) }"}= link_to "Northern Ireland", northern_irelandfilter_url
            %li{:class => "#{'active' if current_page?(engfilter_url) }"}= link_to "England", engfilter_url
            %li{:class => "#{'active' if current_page?(ngofilter_url) }"}= link_to "900 Development NGOs", ngofilter_url


        / /.nav-collapse
        / Main jumbotron for a primary marketing message or call to action
    .container
      #wrapper
        = yield

    %footer#footer
      .container
        %p
          &copy;#{Date.today.year}
          = link_to 'epiGenesys', 'https://www.epigenesys.org.uk', target: '_blank', title: 'Goto the epiGenesys website'

app/views/layouts/plain_error.html.haml
!!!
%html
  %head
    %title ProjectDev - #{content_for(:title)}
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %meta{ :'http-equiv' => 'X-UA-Compatible', content: 'IE=edge' }
    = stylesheet_link_tag    "application", media: :all
    = javascript_include_tag "application"
    = favicon_link_tag '/favicon.ico'

  %body{ class: environment_notice_body_class }
    = render 'layouts/environment_notice'
    .flash-messages
      - flash.each do |name, msg|
        - next unless name == 'alert' || name == 'notice'
        .alert.fade.in
          .container
            - if name == 'notice'
              = fa_icon('check', class: 'flash-success')
            - else
              = fa_icon('warning', class: 'flash-error')
            = msg
            %a{ href: '#', title: 'Hide this message', data: { dismiss: :alert } } Dismiss


    %noscript
      .warning-page-cover
        .alert.alert-info
          %h2 Sorry, it appears that you are using a web browser without JavaScript which prevents us offering you a rich online experience.
          %p Please enable JavaScript or use a different web browser, or alternatively contact the CiCS Helpdesk for assistance.

    #wrap
      %nav#main-nav.navbar.navbar-default.navbar-fixed-top
        .container
          .navbar-header
            %button.navbar-toggle{ data: { target: ".navbar-collapse", toggle: :collapse, type: :button } }
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to :root, class: 'navbar-brand hidden-sm' do
              ProjectDev

          .collapse.navbar-collapse
            %ul.nav.navbar-nav
              = navbar_link_to :root, title: "Go to the home page", identifier: :home do
                = fa_icon 'home'
                Home

      #main-container.container

        = yield

    %footer#footer
      .container
        %p
          &copy;#{Date.today.year}
          = link_to 'epiGenesys', 'https://www.epigenesys.org.uk', target: '_blank', title: 'Goto the epiGenesys website'